# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abtion - Not another digital agency
email: mail@abtion.com
description: > # this means to ignore newlines until "baseurl:"
  Abtion is not another digital agency. We are a software company. We build software that transform companies and make people's life better, easier and more fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abtion.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username: abtion

# Build settings
markdown: kramdown
